### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by clemensloebig** [elkozmon/zoonavigator#13]
How i can use Basic auth ?

**Comment by elkozmon** [comment]
Hi.

This [has been discussed](https://github.com/elkozmon/zoonavigator/issues/8#issuecomment-356569698) before. Sadly there has been no development on the matter since then.

Another option would be to use something like [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) which supports basic auth out-of-the-box and put it in front of ZooNavigator Web container.

That said, I might provide a nicer way to setup basic auth in the near future.

**Comment by clemensloebig** [comment]
Thanks for reply, i'll switch to Zookepper Acl
