### ISSUE TITLE
Refresh ZNode listing

### ISSUE THREAD

**Issue by jhalterman** [elkozmon/zoonavigator#14]
It would be nice to have a refresh button for refreshing the left-hand ZNode listing. Current workaround is to go up a directory and back in to be able to refresh the listing when ZNodes are added/removed.

**Comment by elkozmon** [comment]
This functionality has been there since day one. It used to be the refresh button above the listing itself. Its only purpose was to refresh the listing. Since version 0.3.0 this button has moved to the main toolbar next to the current browsing address and instead of just refreshing the listing, it also refreshes the current editors content.

If it does not work for you then it's a bug and I'd need to reproduce it.

**Comment by jhalterman** [comment]
I didn't realize that. I'm sure it's fine. Thanks!

**Comment by elkozmon** [comment]
No problem. I really appreciate your feature ideas btw 👍
