### ISSUE TITLE
Error: Unable to establish connection with ZooKeeper 

### ISSUE THREAD

**Issue by rodoufu** [elkozmon/zoonavigator#38]
I'm running zookeeper on the host machine on port 2181, and I'm using your docker-compose file to start the zoonavigator.

But I'm getting the following problem:
`Error: Unable to establish connection with ZooKeeper`

I've tried to use my hostname (on the host machine), and also:
localhost:2181
127.0.0.1:2181

But nothing has worked so far.

**Comment by nanshakov** [comment]
you have to change your's zookeeper port. As I know Docker bing internal zookeeper to the same port. 
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                  PORTS                                                  NAMES
....
008ec8bf8353        zookeeper:3.5                      "/docker-entrypoint.…"   26 hours ago        Up 26 hours             2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp, 8080/tcp   zookeeper

**Comment by elkozmon** [comment]
Hi.

A simplified explanation of the problem here is that `zoonavigator-api` container is like a separate machine when running in Docker (in bridged networking mode). You're basically telling it to connect to zookeeper running at `localhost:2181` - i.e. running inside the `api` container at port 2181, and of course, there is none.

Probably the easiest thing to do here is to add `network_mode: host` to both containers in docker-compose file and change the `API_HOST` environment variable of `zoonavigator-web` container to `localhost`.

Sorry for the late reply - I was traveling.

**Comment by rodoufu** [comment]
Thanks @elkozmon, it worked like a charm.
Here I just had to change the api port but it was super easy cause you already have env vars for it on web `API_PORT` and on api `API_HTTP_PORT`.
