### ISSUE TITLE
how can i build the docker images locally?

### ISSUE THREAD

**Issue by babatundebusari** [elkozmon/zoonavigator#4]
is there any way i can build the docker images used locally?

thanks

**Comment by elkozmon** [comment]
Sure! The way I do it requires [sbt](http://www.scala-sbt.org/) and [npm](https://www.npmjs.com/) to be installed. 

First clone both [API](https://github.com/elkozmon/zoonavigator-api) and [Web](https://github.com/elkozmon/zoonavigator-web) repositories. Both already contain a dockerfile but you need to make the production build first. You can do that like so:

API
```
sbt clean play/stage
docker build -t zoonavigator-api .
```

Web
```
npm install
ng build --prod
docker build -t zoonavigator-web .
```

However, the last time I tried to build the Web project it failed presumably due to incompatibility with the newer versions of the dependencies. I intend to fix this in the next days.

**Comment by elkozmon** [comment]
You should be good to go as Web client npm build now works correctly.

**Comment by babatundebusari** [comment]
@elkozmon ok great...will check it out
thanks!

**Comment by nhuray** [comment]
@elkozmon In order to simplify your build process you should take a look to the multi-stage build [released recently in Docker](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds).

**Comment by elkozmon** [comment]
@nhuray thanks for the tip, I will check it out

**Comment by elkozmon** [comment]
@babatundebusari no problem, please let me know if there are any problems

**Comment by elkozmon** [comment]
Hi, I just wanted to let you all know that Docker images can now be built without sbt/npm first building the project. @nhuray thanks for suggesting the multi-stage build!
