### ISSUE TITLE
Standalone service

### ISSUE THREAD

**Issue by yuriymalygin** [elkozmon/zoonavigator#50]
Is it possible to run ZooNavigator as standalone service on dedicated platform (without docker)?

**Comment by elkozmon** [comment]
Hi. No, no at the moment. However, it shouldn't be that hard to make a standalone distribution since the build process would essentially be the same as the one in the Dockerfile. I would be happy to add that to ZooNavigator release process, but it just wasn't a priority. If you'd like to give it a try yourself and maybe submit a PR I'd be happy to help along the way.

**Comment by yuriymalygin** [comment]
Ok. Thx for you answer. I will try to repeat build process from Dockerfile.

**Comment by elkozmon** [comment]
You could simply try copying **_/app_** folder from Docker container onto your host and use just that.

**Comment by elkozmon** [comment]
Hi, I just want to let you know that there is now an official distribution without Docker using the Snap store.

It's not released as a stable version yet but should work fine.

https://snapcraft.io/zoonavigator
https://zoonavigator.elkozmon.com/en/latest/snap/index.html
