### ISSUE TITLE
Need for data directory tree

### ISSUE THREAD

**Issue by jackpgao** [elkozmon/zoonavigator#6]
Can you provide data directory tree?

**Comment by elkozmon** [comment]
Do you mean [the data directory](https://zookeeper.apache.org/doc/r3.1.2/zookeeperAdmin.html#The+Data+Directory) that holds server id and snapshots?

**Comment by jackpgao** [comment]
yeah

**Comment by elkozmon** [comment]
What you're asking would require an extra connection to each Zookeeper host to access the filesystem, since as far as I know, there is no such functionality in Zookeepers client. In my opinion that's too much additional complexity for very little benefit - I don't think there is a common use case that would require this.
